// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Chatroom struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Type      string
	Name      sql.NullString
}

type ChatroomsParticipant struct {
	ChatroomID    uuid.NullUUID
	ParticipantID uuid.NullUUID
}

type Message struct {
	ID         uuid.UUID
	SentAt     time.Time
	UpdatedAt  time.Time
	AuthorID   uuid.NullUUID
	ChatroomID uuid.NullUUID
	Type       string
	Content    sql.NullString
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.NullUUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
	Nickname       string
	Email          string
}
